name: Docker Build

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the build on
  pull_request:
    branches:
      - main  # Replace with the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.AZUREPERIODICTABLE_USERNAME }}
        password: ${{ secrets.AZUREPERIODICTABLE_SECRET }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.AZUREPERIODICTABLE_USERNAME }}/azure-periodic-table-Dockerversion:latest
